
export type IconName =
  | 'Add'
  | 'AddFilled'
  | 'Android'
  | 'ArrowDropDown'
  | 'ArrowLeft'
  | 'ArrowLeftOutlined'
  | 'ArrowRight'
  | 'ArrowRightOutlined'
  | 'AttachFile'
  | 'Bitbucket'
  | 'Chart'
  | 'Chat'
  | 'ChatFilled'
  | 'CheckCircle'
  | 'Checked'
  | 'Close'
  | 'Cloud'
  | 'Copy'
  | 'Dashboard'
  | 'DataBase'
  | 'DeployedCode'
  | 'Draft'
  | 'GithubIcon'
  | 'GoogleIcon'
  | 'Edit'
  | 'Exit'
  | 'Home'
  | 'Inbox'
  | 'Info'
  | 'Loader'
  | 'Location'
  | 'Mail'
  | 'Memory'
  | 'Menu'
  | 'Moon'
  | 'MoreHoriz'
  | 'MoreVert'
  | 'Person'
  | 'Play'
  | 'RadioButtonChecked'
  | 'Rocket'
  | 'RotateRight'
  | 'Settings'
  | 'SmartToy'
  | 'Star'
  | 'StarShield'
  | 'Sun'
  | 'TextSnippet'
  | 'VisibilityOff'
  | 'WarningAmber'
  | 'Web'
  | 'Work'
  | 'ZoomIn'
  | 'ZoomOut'
  | 'ShoppingBag'
  | 'Favourite'
  | 'FavouriteFilled'
  | 'Sales'
  | 'Views'
  | 'Reload'
  | 'Notification'
  | 'Logo'
  | 'Hamburger'
  | 'LargeArrowRight'
  | 'Search'
  | 'Filter'
  | 'Coin';

export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export interface IconProps {
  name: IconName;
  size?: IconSize;
  className?: string;
  color?: string;
  onClick?: () => void;
  'data-testid'?: string;
}
